name: "Build Reproducer Container"

on:
  push:

permissions:
  contents: read

jobs:
  build-reproducer-container:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch:
          - aarch64
          - ppc64le
          - s390x
          - x86_64
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Container
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          sudo apt-get -y update
          sudo apt-get -y install podman
          podman build --arch ${{ matrix.arch }} -t ghcr.io/$GITHUB_REPOSITORY_OWNER/llvm-snapshots-reproducer:${{ matrix.arch }} containers/reproducer
          podman login -u ${{ github.actor }} -p $GITHUB_TOKEN ghcr.io
          podman push ghcr.io/$GITHUB_REPOSITORY_OWNER/llvm-snapshots-reproducer:${{ matrix.arch }}
