name: Mass Rebuild Bisect

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      pkg:
        description: "The package to bisect"
        required: true
        type: string
      arch:
        description: "The architecture to test"
        required: false
        default: x86_64
        type: choice
        options:
          - x86_64
          - aarch64
          - ppc64le
          - s390x

  workflow_call:
    inputs:
      pkg:
        description: "The package to bisect"
        required: true
        type: string
      arch:
        description: "The architecture to test"
        required: false
        default: x86_64
        type: string

jobs:
  mass-rebuild-bisect:
    runs-on: ubuntu-24.04
    container:
      image: "ghcr.io/${{ github.repository_owner }}/llvm-snapshots-reproducer"
    steps:
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 8G
          key: bisect
      - working-directory: /root/llvm-project/
        run: |
          bash bisect.sh ${{ inputs.pkg }}

      - if: always()
        working-directory: /root/llvm-project
        run: |
          git bisect log
