name: "Mass rebuild reporter"

on:
  schedule:
    - cron: "40 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-for-rebuild:
    runs-on: ubuntu-24.04
    steps:
      - name: Check for existing report
        uses: actions/github-script@v7
        id: check-existing
        with:
          result-encoding: string
          script: |
            const issues = await github.rest.search.issuesAndPullRequests({
              q: "label:mass-rebuild+state:open",
            });

            console.log(issues)
            if (issues.data.total_count > 0)
                return "skip"
            return "";


      - name: Create Report
        if: steps.check-existing.outputs.result != 'skip'
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Create Report!")




