name: "Mass rebuild reporter"

on:
  schedule: "40 * * * *"
  workflow_dispatch:

permisons:
  contents: read

jobs:
  check-for-rebuild:
    runs-on: ubuntu-24.04
    steps:
      - name: Check for existing report
        uses: actions/github-script@v7
        with:
          script: |
            const issues = github.rest.search.issuesAndPullRequests({
              q: "label:mass-rebuild+state:open",
            });

            console.log(issues) 
